# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad7a0b645cab71cd3b84d1eeb481b05de118d8c3dcff026bf27fbab67f875fefdedf8d2c1ace0b63cf74330561da383d0acad27e2084aee2ded668b130162c93

test:
  secret_key_base: 8e2008097003f361a2a7aa9d11cc145ec77b77d4cac54786bcffe74bc96a19ab71f953d93872a2a2bc20124be3a9ccf3d2351f90ee26f88a926478df4634d38e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
